CREATE DATABASE IF NOT EXISTS talesof;

USE talesof;

DROP TABLE IF EXISTS Item_in_inventory;
DROP TABLE IF EXISTS Save_state;
DROP TABLE IF EXISTS Save;
DROP TABLE IF EXISTS Character_state;
DROP TABLE IF EXISTS Save_point;
DROP TABLE IF EXISTS Change_password;
DROP TABLE IF EXISTS Settings;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Item;
